import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/components/Navbar";

const forcedSquare = localFont({
    src: "../assets/fonts/Forced-Square.ttf",
    variable: "--font-forced-square",
});

const goodTiming = localFont({
    src: "../assets/fonts/Good-Timing.otf",
    variable: "--font-good-timing",
});

const monsterrat = Montserrat({
    subsets: ["latin"],
    variable: "--font-montserrat",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fr">
            <body
                className={`${goodTiming.variable} ${forcedSquare.variable} ${monsterrat.variable} bg-background bg-cover bg-no-repeat min-h-screen`}
            >
                <Navbar />
                {children}
            </body>
        </html>
    );
}
