version: "3.8"

services:
    # Service pour Next.js (Frontend)
    frontend:
        build:
            context: frontend
            dockerfile: Dockerfile
        working_dir: /app
        volumes:
            - ./frontend:/app
            - /app/node_modules
        ports:
            - "3000:3000"
        command: sh -c "yarn install && yarn dev"
        environment:
            - NEXT_PUBLIC_API_URL=http://localhost:1337 # URL du backend Strapi
        depends_on:
            - strapi

    # Service pour Strapi (Backend)
    strapi:
        container_name: strapi
        build:
            context: backend
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./backend:/srv/app
            - /srv/app/node_modules
        ports:
            - "1337:1337"
        environment:
            DATABASE_CLIENT: postgres
            DATABASE_HOST: db
            DATABASE_PORT: 5432
            DATABASE_NAME: illusion_db
            DATABASE_USERNAME: illusion
            DATABASE_PASSWORD: illusion_admin
            DATABASE_SSL: "false"
        depends_on:
            - db

    # Service pour PostgreSQL
    db:
        image: postgres:15
        environment:
            POSTGRES_DB: illusion_db
            POSTGRES_USER: illusion
            POSTGRES_PASSWORD: illusion_admin
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    postgres_data:
        driver: local
